### ISSUE TITLE
Missing example/initilisation code for TMCM (e.g. 1270) CANopen

### ISSUE THREAD

**Issue by Zebrafish007** [LukeSkywalker92/pyTMCL#2]
Hi,

I am struggling to get my ESD CAN-USB/2 device working with the python-tmcl (pyTMCL) software. What do I need to write for "serial_port = Serial("/dev/tty.usbmodem1241")" for below code as I have an usb/can interface device.

Cheers,

Installed:
Win 10 Pro, x64
python 3.7.4
pyUSB 1.0.2
LibUSB1 1.7.1
CAN 3.3.2

from serial import Serial
from time import sleep
import TMCL
serial-address as set on the TMCM module.

MODULE_ADDRESS = 1
Open the serial port presented by your rs485 adapter

serial_port = Serial("/dev/tty.usbmodem1241")
Create a Bus instance using the open serial port

bus = TMCL.connect(serial_port)
Get the motor

motor = bus.get_motor(MODULE_ADDRESS)
From this point you can start issuing TMCL commands
to the motor as per the TMCL docs. This example will
rotate the motor left at a speed of 1234 for 2 seconds

motor.rotate_left(1234)
sleep(2)
motor.stop()

**Comment by LukeSkywalker92** [comment]
Hi,
I never tried to use this on windows, but I think you should write the name of the device that is shown in the device manager. So something like COM1.

**Comment by emma-branigan** [comment]
Hi there, 

As a user of the pyTMCL module on Windows, I can confirm that the line should read:

serial_port = Serial('COM*')

Replace * with the number that appears in the Device Manager once your USB device is connected

**Comment by Zebrafish007** [comment]
Hi Emma,

The issue is that serial_port = Serial('COM*') can't be used because the CAN-USB is not showing as a 'COM*' device. Using Zadig 2.4 to change the drivers in any selectable from the presented list didn't work either.

In the meantime I've got this far using the ntcan python lib from ESD:

MODULE_ADDRESS = 0
net=0                                   # logical CAN Network [0, 255]
    RxQS=2000                               # RxQueueSize [0, 10000]
    RxTO=2000                               # RxTimeOut in Millisconds
    TxQS=1                                  # TxQueueSize [0, 10000]
    TxTO=1000                               # TxTimeOut in Millseconds
    #cifFlags=                              # Flags
    cif = ntcan.CIF(net,RxQS,RxTO,TxQS,TxTO)
    print ('"Initialize CANBUS: %s"' % cif)
    sys.stdout.flush()

    # set baudrate 0 = 1MBaud
    # CAN-API-Description
#    cif.baudrate = 0
    bus = pyTMCL.connect(cif, CAN=False)
    print ('bus   :', bus)
    sys.stdout.flush()

    motor = bus.get_motor(MODULE_ADDRESS)
    print ('motor action 0 : ', motor)
    motor.target_speed = 20000 
    print ('motor action 1 : ', motor)
    motor.rotate_left = 12340
    print ('motor action 2 : ', motor)
    sys.stdout.flush()
    
    sleep(5)
    try:
        motor.stop()
        print ('And the crowd cheered and echood "Throw us a party"!')
        sys.stdout.flush()
    except can.CanError:
        print("Message NOT sent")
        sys.stdout.flush()

**Comment by Zebrafish007** [comment]
import ntcan
import pyTMCL

**Comment by Zebrafish007** [comment]
With libusb-win32 (1.2.6.0) in device-manager it shows up under "libusb-win32 devices". With WinUSB (6.1.7600.16385) its under "Unversal Serial Bus devices. Then with "libbusbK (3.0.7.0) it shows as "libusbK USB Devices".

There also appears some class inheritance issues for all methods under self.axis in the motor class.

**Comment by Zebrafish007** [comment]
With libusb-win32 (1.2.6.0) in device-manager it shows up under "libusb-win32 devices". With WinUSB (6.1.7600.16385) its under "Unversal Serial Bus devices. Then with "libbusbK (3.0.7.0) it shows as "libusbK USB Devices". But with  "USB Serial (CDC) it now shows under "Ports (COM & LPT) as "USB2292(COM4), however, its still not working.

There also appears some class inheritance issues for all methods under self.axis in the motor class.

**Comment by cl0v3x** [comment]
Hello,
I dont know weather this question is still opend or not, but at least Im gonna try.

I am using Python on Win10 an changed the serial name to serial_port = Serial('COM3') like @emma-branigan recomended. But sadly as soon as I try to run the programm, this Error apperars:

`PS` C:\Users\root\Desktop\PYProgramme> & C:/Users/root/AppData/Local/Programs/Python/Python39/python.exe c:/Users/root/Desktop/PYProgramme/motor.py
Traceback (most recent call last):
  File "c:\Users\root\Desktop\PYProgramme\motor.py", line 9, in <module>
    serial_port = Serial('COM3')
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\serial\serialwin32.py", line 64, in open    
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM3': PermissionError(13, 'Zugriff verweigert', None, 5)``

Could it be that I have to change some permissions or something? Does somebody know how I can fiy this?
